const { app } = require("electron");
const path = require("node:path");

const state = {
  isDev: !app.isPackaged,
  isQuitting: false,
  sessionAllowedPaths: new Set(),
  appStorageRootCache: null,
  appOutputsRootCache: null,
  mainWindow: null,
  splashWindow: null,
  py: null,
  requestSeq: 0,
  pending: new Map(),
  SPLASH_PROGRESS_FALLBACK_MS: 3200,
  splashProgressCompletionPromise: Promise.resolve(),
  resolveSplashProgressCompletion: null,
  pyRestartTimestamps: [],
  PY_MAX_RESTARTS: 5,
  PY_RESTART_WINDOW_MS: 30000,
  PY_RESET_COOLDOWN_MS: 300000,
  pyDisabled: false,
  pyDisabledTimestamp: 0,
  PY_CALL_TIMEOUT_MS: 60000,
  WINDOW_STATE_FILE: path.join(app.getPath("userData"), "window-state.json"),
  THEME_FILE: path.join(app.getPath("userData"), "theme.json"),
  LEGAL_CONSENT_FILE: path.join(app.getPath("userData"), "legal-consent.json"),
  APP_LEGAL_CONSENT_VERSION: "2026-05-10",
  THEME_BG_MAP: {
    dark: "#0b1020",
    light: "#f3f3f3",
    "one-dark": "#282c34",
    monokai: "#272822",
    dracula: "#282a36",
    "solarized-light": "#fdf6e3",
    "github-light": "#ffffff",
  },
  THEME_FAMILY_MAP: {
    dark: "dark",
    "one-dark": "dark",
    monokai: "dark",
    dracula: "dark",
    light: "light",
    "solarized-light": "light",
    "github-light": "light",
  },
  THEME_TOPBAR_MAP: {
    dark: "#131a33",
    "one-dark": "#21252b",
    monokai: "#1e1f1c",
    dracula: "#21222c",
    light: "#e8e8e8",
    "solarized-light": "#eee8d5",
    "github-light": "#f6f8fa",
  },
  THEME_SYMBOL_MAP: {
    dark: "#e0e0e0",
    "one-dark": "#abb2bf",
    monokai: "#f8f8f2",
    dracula: "#f8f8f2",
    light: "#1e1e1e",
    "solarized-light": "#586e75",
    "github-light": "#1f2328",
  },
  DEFAULT_WINDOW_STATE: {
    width: 1280,
    height: 820,
    x: undefined,
    y: undefined,
    isMaximized: false,
  },
  APP_DATA_DIR: null,
};

module.exports = state;
